PracticeProject/Models/Course.cs
using PracticeProject.Data.Enum;

namespace PracticeProject.Models
{
    public class Course
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string? Image { get; set; }
        public CourseStatus IsOpen { get; set; }

        public virtual User? User { get; set; }
        public virtual List<Lesson> Lessons { get; set; }
        public virtual List<CourseGrupa> courseGrupas { get; set; }
        public virtual List<CourseRole>? courseRoles { get; set; }
    }
}

PracticeProject/Models/HomeWork.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PracticeProject.Models
{
    public class HomeWork
    {
        [Key]
        public int Id { get; set; }
        public int OrderNumber { get; set; }
        public string Task { get; set; }

        public virtual Lesson Lesson { get; set; }
    }
}

PracticeProject/Models/LabWork.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PracticeProject.Models
{
    public class LabWork
    {
        [Key]
        public int Id { get; set; }
        public string Task { get; set; }

        public virtual Lesson Lesson { get; set; }
    }
}

PracticeProject/Models/TextWork.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PracticeProject.Models
{
    public class TextWork
    {
        [Key]
        public int Id { get; set; }
        public int OrderNumber { get; set; }
        public string Task { get; set; }

        public virtual Lesson Lesson { get; set; }
    }
}

PracticeProject/Models/User.cs
using Microsoft.AspNetCore.Identity;

namespace PracticeProject.Models
{
    //для учителей вкладку по типу мои курсы
    public class User : IdentityUser
    {
        public string? GrupaId { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string? ProfileImage { get; set; }
        public virtual Grupa? Grupa { get; set; }
        public virtual IList<Course>? Course { get; set; }

        //список дз к примеру

    }
}

PracticeProject/ViewModels/CreateCourseViewModel.cs
using PracticeProject.Data.Enum;
using PracticeProject.Models;

namespace PracticeProject.ViewModels
{
    public class CreateCourseViewModel
    {
        public string Name { get; set; }
        public IFormFile Image { get; set; }
        public CourseStatus IsOpen { get; set; }

       // public CreateLessonViewModel? LessonVM { get; set; }
        public virtual List<CourseGrupa>? CourseGrupas { get; set; }
        public virtual List<CourseRole>? CourseRoles { get; set; }
    }
}

PracticeProject/ViewModels/CreateHomeWorkViewModel.cs
namespace PracticeProject.ViewModels
{
    public class CreateHomeWorkViewModel
    {
        public int OrderNumber { get; set; }
        public string Task { get; set; }
        public int lessonId { get; set; }
    }
}

PracticeProject/ViewModels/CreateLabWorkViewModel.cs
namespace PracticeProject.ViewModels
{
    public class CreateLabWorkViewModel
    {
        public string Task { get; set; }
        public int lessonId { get; set; }
    }
}

PracticeProject/ViewModels/CreateLessonViewModel.cs
using PracticeProject.Data.Enum;

namespace PracticeProject.ViewModels
{
    public class CreateLessonViewModel
    {
        public int OrderNumber { get; set; }
        public string Name { get; set; }
        public CourseStatus IsOpen { get; set; }
        public int courseId { get; set; }
    }
}

PracticeProject/ViewModels/HomeWorkViewModel.cs
namespace PracticeProject.ViewModels
{
    public class HomeWorkViewModel
    {
        public int Id { get; set; }
        public int OrderNumber { get; set; }
        public string Task { get; set; }
        public int lessonId { get; set; }
    }
}

PracticeProject/ViewModels/LabWorkViewModel.cs
namespace PracticeProject.ViewModels
{
    public class LabWorkViewModel
    {
        public int Id { get; set; }
        public string Task { get; set; }
        public int lessonId { get; set; }
    }
}

PracticeProject/ViewModels/TextWorkViewModel.cs
namespace PracticeProject.ViewModels
{
    public class TextWorkViewModel
    {
        public int Id { get; set; }
        public int OrderNumber { get; set; }
        public string Task { get; set; }
        public int lessonId { get; set; }
    }
}

PracticeProject/ViewModels/UserViewModel.cs
namespace PracticeProject.ViewModels
{
    public class UserViewModel
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string? Grupa { get; set; }
        public string? Image { get; set; }
        public List<string> RolesName { get; set; }
    }
}

PracticeProject/Controllers/HomeWorkController.cs
using Microsoft.AspNetCore.Mvc;
using PracticeProject.Data;
using PracticeProject.Interface;
using PracticeProject.Models;
using PracticeProject.Repository;
using PracticeProject.ViewModels;

namespace PracticeProject.Controllers
{
    public class HomeWorkController : Controller
    {
        private readonly IHomeworkRepository _homeworkRepository;

        public HomeWorkController(IHomeworkRepository homeworkRepository)
        {
            _homeworkRepository = homeworkRepository;
        }
        public IActionResult Create(int courseId, int lessonNumber)
        {
            var lesson = _homeworkRepository.GetBycourseIdAndlessonIdAsync(courseId, lessonNumber);
            HomeWorkViewModel homeWorkVM = new HomeWorkViewModel()
            {
                //OrderNumber = _dbContext.Lessons.FirstOrDefault(x => x.Course.Id == courseId && x.OrderNumber == lessonNumber).Id,
                lessonId = lesson.Id,
                OrderNumber = _homeworkRepository.GetLastWorkOrderNumberByLessonId(lesson.Id)

            };
            
            return View(homeWorkVM);
        }

        [HttpPost]
        public async Task<IActionResult> Create(HomeWorkViewModel homeWorkVM)
        {

            if (!ModelState.IsValid)
            {
                return View(homeWorkVM);
            }
            var lesson = _homeworkRepository.GetLessonById(homeWorkVM.lessonId);
            HomeWork homeWork = new HomeWork()
            {
                OrderNumber = homeWorkVM.OrderNumber,
                Task = homeWorkVM.Task,
                Lesson = _homeworkRepository.GetLessonById(homeWorkVM.lessonId)
            };
            _homeworkRepository.Add(homeWork);
            return RedirectToAction("Index", "Lesson", new { courseId = lesson.Course.Id, lessonNumber = lesson.OrderNumber });
        }



        public async Task<IActionResult> Edit(int id)
        {


            var homeWork = await _homeworkRepository.GetByIdAsync(id);


            if (homeWork == null)
                return View("Error");
            var homeWorkVM = new HomeWorkViewModel
            {
                Id = id,
                Task = homeWork.Task,
                OrderNumber = homeWork.OrderNumber,
                lessonId = homeWork.Lesson.Id
            };

            return View(homeWorkVM);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, HomeWorkViewModel homeWorkVM)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Failed to edit text");
                return View("Edit", homeWorkVM);
            }



            var homeworkEdit = await _homeworkRepository.GetByIdAsyncNoTracking(id);
            if (homeworkEdit != null)
            {

                var homework = new HomeWork
                {
                    Id = id,
                    Task = homeWorkVM.Task,
                    OrderNumber = homeWorkVM.OrderNumber,
                    Lesson = _homeworkRepository.GetLessonById(homeWorkVM.lessonId)
                };

                _homeworkRepository.Update(homework);

                return RedirectToAction("Index", "Lesson", new { courseId = homework.Lesson.Course.Id, lessonNumber = homework.Lesson.OrderNumber });
            }

            return View(homeWorkVM);

        }

        public async Task<IActionResult> Delete(int id)
        {
            var homeworkDetails = await _homeworkRepository.GetByIdAsync(id);
            var lesson = homeworkDetails.Lesson;
            if (homeworkDetails == null)
                return View("Error");
            _homeworkRepository.Delete(homeworkDetails);


            return RedirectToAction("Index", "Lesson", new { courseId = lesson.Course.Id, lessonNumber = lesson.OrderNumber });

        }
    }
}

PracticeProject/Controllers/LabWorkController.cs
using Microsoft.AspNetCore.Mvc;
using PracticeProject.Interface;
using PracticeProject.Models;
using PracticeProject.Repository;
using PracticeProject.ViewModels;

namespace PracticeProject.Controllers
{
    public class LabWorkController : Controller
    {
        private readonly ILaboratoryRepository _laboratoryRepository;

        public LabWorkController(ILaboratoryRepository laboratoryRepository)
        {
            _laboratoryRepository = laboratoryRepository;
        }
        public IActionResult Create(int courseId, int lessonNumber)
        {
            var lesson = _laboratoryRepository.GetBycourseIdAndlessonIdAsync(courseId, lessonNumber);
            LabWorkViewModel labWorkVM = new LabWorkViewModel()
            {
                //OrderNumber = _dbContext.Lessons.FirstOrDefault(x => x.Course.Id == courseId && x.OrderNumber == lessonNumber).Id,
                lessonId = lesson.Id

            };

            return View(labWorkVM);
        }

        [HttpPost]
        public async Task<IActionResult> Create(LabWorkViewModel labWorkVM)
        {

            if (!ModelState.IsValid)
            {
                return View(labWorkVM);
            }
            var lesson = _laboratoryRepository.GetLessonById(labWorkVM.lessonId);
            LabWork labWork = new LabWork()
            {
                Task = labWorkVM.Task,
                Lesson = _laboratoryRepository.GetLessonById(labWorkVM.lessonId)
            };
            _laboratoryRepository.Add(labWork);
            return RedirectToAction("Index", "Lesson", new { courseId = lesson.Course.Id, lessonNumber = lesson.OrderNumber });
        }

        public async Task<IActionResult> Edit(int id)
        {


            var labWork = await _laboratoryRepository.GetByIdAsync(id);


            if (labWork == null)
                return View("Error");
            var labWorkVM = new LabWorkViewModel
            {
                Id = id,
                Task = labWork.Task,
                lessonId = labWork.Lesson.Id
            };

            return View(labWorkVM);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, LabWorkViewModel labWorkVM)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Failed to edit text");
                return View("Edit", labWorkVM);
            }



            var labWorkEdit = await _laboratoryRepository.GetByIdAsyncNoTracking(id);
            if (labWorkEdit != null)
            {

                var labWork = new LabWork
                {
                    Id = id,
                    Task = labWorkVM.Task,
                    Lesson = _laboratoryRepository.GetLessonById(labWorkVM.lessonId)
                };

                _laboratoryRepository.Update(labWork);

                return RedirectToAction("Index", "Lesson", new { courseId = labWork.Lesson.Course.Id, lessonNumber = labWork.Lesson.OrderNumber });
            }

            return View(labWorkVM);

        }
        public async Task<IActionResult> Delete(int id)
        {
            var labworkDetails = await _laboratoryRepository.GetByIdAsync(id);
            var lesson = labworkDetails.Lesson;
            if (labworkDetails == null)
                return View("Error");
            _laboratoryRepository.Delete(labworkDetails);


            return RedirectToAction("Index", "Lesson", new { courseId = lesson.Course.Id, lessonNumber = lesson.OrderNumber });

        }
    }
}

PracticeProject/Controllers/TextWorkController.cs
using Microsoft.AspNetCore.Mvc;
using PracticeProject.Data;
using PracticeProject.Interface;
using PracticeProject.Models;
using PracticeProject.Repository;
using PracticeProject.ViewModels;

namespace PracticeProject.Controllers
{
    public class TextWorkController : Controller
    {
        private readonly ITextRepository _textRepository;

        public TextWorkController(ITextRepository textRepository)
        {
            _textRepository = textRepository;
        }
        public IActionResult Create(int courseId, int lessonNumber)
        {
            var lesson = _textRepository.GetBycourseIdAndlessonIdAsync(courseId, lessonNumber);
            TextWorkViewModel textWorkVM = new TextWorkViewModel()
            {
                //OrderNumber = _dbContext.Lessons.FirstOrDefault(x => x.Course.Id == courseId && x.OrderNumber == lessonNumber).Id,
                lessonId = lesson.Id,
                OrderNumber = _textRepository.GetLastTextWorkOrderNumberByLessonId(lesson.Id)

            };

            return View(textWorkVM);
        }

        [HttpPost]
        public async Task<IActionResult> Create(TextWorkViewModel textWorkVM)
        {

            if (!ModelState.IsValid)
            {
                return View(textWorkVM);
            }
            var lesson = _textRepository.GetLessonById(textWorkVM.lessonId);
            TextWork textWork = new TextWork()
            {
                OrderNumber = textWorkVM.OrderNumber,
                Task = textWorkVM.Task,
                Lesson = _textRepository.GetLessonById(textWorkVM.lessonId)
            };
            _textRepository.Add(textWork);
            return RedirectToAction("Index", "Lesson", new { courseId = lesson.Course.Id, lessonNumber = lesson.OrderNumber });
        }


        public async Task<IActionResult> Edit(int id)
        {


            var textWork = await _textRepository.GetByIdAsync(id);


            if (textWork == null)
                return View("Error");
            var textVM = new TextWorkViewModel
            {
                Id = id,
                Task = textWork.Task,
                OrderNumber = textWork.OrderNumber,
                lessonId = textWork.Lesson.Id
            };

            return View(textVM);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, TextWorkViewModel textVM)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Failed to edit text");
                return View("Edit", textVM);
            }



            var textEdit = await _textRepository.GetByIdAsyncNoTracking(id);
            if (textEdit != null)
            {

                var text = new TextWork
                {
                    Id = id,
                    Task = textVM.Task,
                    OrderNumber = textVM.OrderNumber,
                    Lesson = _textRepository.GetLessonById(textVM.lessonId)
                };

                _textRepository.Update(text);

                return RedirectToAction("Index", "Lesson", new { courseId = text.Lesson.Course.Id, lessonNumber = text.Lesson.OrderNumber });
            }

            return View(textVM);

        }

        public async Task<IActionResult> Delete(int id)
        {
            var textDetails = await _textRepository.GetByIdAsync(id);
            var lesson = textDetails.Lesson;
            if (textDetails == null)
                return View("Error");
            _textRepository.Delete(textDetails);


            return RedirectToAction("Index", "Lesson", new { courseId = lesson.Course.Id, lessonNumber = lesson.OrderNumber });

        }
    }

}

PracticeProject/Views/Shared/_Courses.cshtml
@using PracticeProject.Data.Enum;
@model IList<Course>


@foreach (var course in Model)
{
    <div class="course">
        <h3>@course.Name</h3>
        @foreach (var grupa in course.courseGrupas)
        {
            <p>@grupa.Grupa.Code</p>
        }
        @if (course.Lessons.Any())
        {
            if (course.Lessons.Count(x => x.IsOpen == CourseStatus.Open) > 0)
            {
                var lesson = course.Lessons.FirstOrDefault(x => x.IsOpen == CourseStatus.Open);
                if (lesson != null)
                {
                    <a href="@Url.Action("Index", "Lesson", new {courseId = course.Id, lessonNumber = lesson.OrderNumber})">
                        Start-->
                    </a>
                }
            }
            else if (User.IsInRole("admin"))
            {
                <a href="@Url.Action("Index", "Lesson", new {courseId = course.Id, lessonNumber = 1})">
                    Start-->
                </a>
            }
        }
        @if (course.User != null)
        {
            @if (course.User.Id == User.GetUserId() || User.IsInRole("admin"))
            {
                <a style="background-color:forestgreen;" href="@Url.Action("Create", "Lesson", new {courseId = course.Id})">
                    + Add Lesson
                </a>
                <a href="@Url.Action("Edit", "Course", new {id = course.Id})">
                    Edit Course
                </a>
                <a style="background-color: red;" href="@Url.Action("Delete", "Course", new {id = course.Id})">
                    Delete Course
                </a>
            }

        }
        
    </div>
}

PracticeProject/Views/Shared/_CreateCourse.cshtml
@using PracticeProject.Data.Enum;
@using PracticeProject.ViewModels;
@model CreateCourseViewModel
@{
}



<div class="form-group">
    <label asp-for="Name">Course Name</label>
    <input asp-for="Name" required>
    <span asp-validation-for="Name" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Image">ImageFile</label>
    <input asp-for="Image" type="file">
</div>
<div class="form-group">
    <label asp-for="IsOpen">Course status</label>
    @{
        var statusValues = Enum.GetValues(typeof(CourseStatus)).Cast<CourseStatus>().ToList();
        statusValues.Reverse();
    }

    <select asp-for="IsOpen">
        @*asp-items="@Html.GetEnumSelectList<CourseStatus>()"*@
        @foreach (var status in statusValues)
        {
            <option value="@status">@status</option>
        }
    </select>

    <span asp-validation-for="IsOpen" class="text-danger"></span>
</div>

<div class="form-group">
    <p>
        Grups <span id="fold"></span>
        <div id="list">
            <div class="checkbox-list">
                @foreach (var grup in ViewBag.Grups)
                {
                    <label class="custom-checkbox">
                        <input type="checkbox" name="selectedGrups" value="@grup.Code" class="custom-control-input">
                        <span class="custom-control-label">@grup.Code</span>
                    </label>
                    <br />
                }
            </div>
        </div>
        @Html.ValidationMessageFor(model => model.CourseGrupas, "", new { @class = "text-danger" })
    </p>
</div>

@if (User.IsInRole("admin"))
{
    <div class="form-group">
        <p>
            Roles <span id="fold"></span>
            <div id="list">
                <div class="checkbox-list">
                    @foreach (var role in ViewBag.Roles)
                    {
                        <label class="custom-checkbox">
                            <input type="checkbox" name="selectedRoles" value="@role.Id" class="custom-control-input">
                            <span class="custom-control-label">@role.Name</span>
                        </label>
                        <br />
                    }
                </div>
            </div>
            @Html.ValidationMessageFor(model => model.CourseRoles, "", new { @class = "text-danger" })
        </p>
    </div>

}


@*<script>
    var list = document.getElementById("list");
    var fold = document.getElementById("fold");

    var open = function () {
        fold.innerHTML = '▼';
        list.style.display = 'block';
        fold.onclick = close;
    };
    var close = function () {
        fold.innerHTML = '◀';
        list.style.display = 'none';
        fold.onclick = open;
    };

    close();
</script>
*@

PracticeProject/Views/Shared/_CreateHomework.cshtml
@using PracticeProject.ViewModels;
@model HomeWorkViewModel

<input type="hidden" asp-for="lessonId" />
<input type="hidden" asp-for="Id" />

<div class="form-group">
    <label asp-for="Task">Task</label>
    <textarea class="form-control" style="margin-top: 20px;" rows="5" placeholder="Add your task..." name="Task">@Model.Task</textarea>
    <span asp-validation-for="Task" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="OrderNumber">OrderNumber</label>
    <input asp-for="OrderNumber" required>
    <span asp-validation-for="OrderNumber" class="text-danger"></span>
</div>

PracticeProject/Views/Shared/_CreateLabWork.cshtml
@using PracticeProject.ViewModels;
@model LabWorkViewModel

<input type="hidden" asp-for="lessonId" />
<input type="hidden" asp-for="Id" />

<div class="form-group">
    <label asp-for="Task">Task</label>
    <textarea class="form-control" style="margin-top: 20px;" rows="15" placeholder="Add your tasks..." name="Task">@Model.Task</textarea>
    <span asp-validation-for="Task" class="text-danger"></span>
</div>

PracticeProject/Views/Shared/_CreateLesson.cshtml
@using PracticeProject.Data.Enum;
@using PracticeProject.ViewModels;
@model LessonViewModel

<input type="hidden" asp-for="courseId" />
<div class="form-group">
    <label asp-for="Name">Lesson Name</label>
    <input asp-for="Name" required>
    <span asp-validation-for="Name" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="OrderNumber">OrderNumber</label>
    <input asp-for="OrderNumber" required>
    <span asp-validation-for="OrderNumber" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="IsOpen">Lesson status</label>
    <select asp-for="IsOpen" asp-items="@Html.GetEnumSelectList<CourseStatus>()">
        
    </select>

    <span asp-validation-for="IsOpen" class="text-danger"></span>
</div>

PracticeProject/Views/Shared/_CreateText.cshtml
@using PracticeProject.ViewModels;
@model TextWorkViewModel

<input type="hidden" asp-for="lessonId" />
<input type="hidden" asp-for="Id" />

<div class="form-group">
    <label asp-for="Task">Task</label>
    <div>
        <button type="button" onclick="insertTag('[ж][/ж]')">ж</button>
        <button type="button" onclick="insertTag('[к][/к]')">к</button>
        <button type="button" onclick="insertTag('[ч][/ч]')">ч</button>
    </div>
    <textarea class="form-control" style="margin-top: 20px;" rows="5" placeholder="Add your text..." name="Task" id="taskTextarea">@Model.Task</textarea>
    <span asp-validation-for="Task" class="text-danger"></span>
</div>


<div class="form-group">
    <label asp-for="OrderNumber">OrderNumber</label>
    <input asp-for="OrderNumber" required>
    <span asp-validation-for="OrderNumber" class="text-danger"></span>
</div>

<script>
    function insertTag(tag) {
        var textarea = document.getElementById('taskTextarea');
        var text = textarea.value;
        var selectionStart = textarea.selectionStart;
        var selectionEnd = textarea.selectionEnd;

        var selectedText = text.substring(selectionStart, selectionEnd);

        // Проверьте, если нет выделенного текста, то просто вставьте теги в текущую позицию курсора
        if (selectionStart === selectionEnd) {
            var newText = text.substring(0, selectionStart) + tag + text.substring(selectionEnd);
            textarea.value = newText;
            // Установите курсор после вставленных тегов
            textarea.selectionStart = selectionStart + tag.length;
            textarea.selectionEnd = selectionStart + tag.length;
        } else {
            // Вставьте теги вокруг выделенного текста
            var newText = text.substring(0, selectionStart) + tag + selectedText + tag + text.substring(selectionEnd);
            textarea.value = newText;
            // Установите курсор после закрывающего тега
            textarea.selectionStart = selectionEnd + tag.length * 2;
            textarea.selectionEnd = textarea.selectionStart;
        }
    }

</script>

PracticeProject/Views/Shared/_HomeWork.cshtml
@model ICollection<HomeWork>

<style>
    .hidden {
        display: none;
    }
</style>

@foreach (var item in Model)
{
    <input type="radio" name="radio" id="radio @item.OrderNumber">
    <label for="radio @item.OrderNumber">Homework @item.OrderNumber</label>
    @if (item.Lesson.Course.User != null)
    {
        @if (User.Identity.IsAuthenticated && User.IsInRole("admin") || item.Lesson.Course.User.Id == User.GetUserId())
        {
            <a href="@Url.Action("Edit", "HomeWork", new {id = item.Id})">Edit</a>
        }
    }
    <br />
    <br />
}

@foreach (var item in Model)
{
    <br />
    <div id="text @item.OrderNumber" class="hidden">@Html.Raw(item.Task)</div>
    <br />
}

<script>
    const radioButtons = document.querySelectorAll('input[type="radio"]');
    const texts = document.querySelectorAll('div[id^="text"]');

    radioButtons.forEach((radio, index) => {
        radio.addEventListener('change', () => {
            texts.forEach((text, i) => {
                text.style.display = i === index && radio.checked ? 'block' : 'none';
            });
        });
    });
</script>

PracticeProject/Views/Shared/_LabWork.cshtml
@model ICollection<LabWork>

<style>

    .edit {
        text-align: center;
        background-color: blueviolet; /* Темно-зеленый цвет */
        color: #fff;
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        font-size: 18px;
        cursor: pointer;
        transition: background-color 0.2s ease-in-out;
        display: block;
        text-decoration: none;
        margin: 5px auto;
        width: 90%;
    }

        .edit:hover {
            background-color: #8a2999; /* Светлый оттенок сине-фиолетового цвета при наведении */
            color: #fff;
            text-decoration: none;
        }
</style>

@foreach (var item in Model)
{
    @if (item.Lesson.Course.User != null)
    {
        @if (User.Identity.IsAuthenticated && User.IsInRole("admin") || item.Lesson.Course.User.Id == User.GetUserId())
        {
            <a class="edit" href="@Url.Action("Edit", "LabWork", new {id = item.Id})">Edit</a>
        }
    }
    <br />
    @Html.Raw(item.Task)
}

PracticeProject/Views/Shared/_TextWork.cshtml
@model ICollection<TextWork>

<style>
    .add {
        text-align: center;
        background-color: #006400; /* Темно-зеленый цвет */
        color: #fff;
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        font-size: 18px;
        cursor: pointer;
        transition: background-color 0.2s ease-in-out;
        display: block;
        text-decoration: none;
        margin: 5px auto;
        width: 90%;
    }

        .add:hover {
            background-color: #00cc00; /* Светло-зеленый цвет при наведении */
            color: #fff;
            text-decoration: none;
        }


    .workText {
        position: relative;
        padding: 10px;
        margin-top: 25px;
    }

    .sel {
        cursor: pointer; /* Добавьте курсор-указатель, чтобы указать, что элемент кликабелен */
    }

        .sel:hover {
            background-color: #ff9999;
            border-radius: 7px;
            color: black;
        }

    .popup {
        font-size: 28px;
        display: none;
        position: absolute;
        top: 0;
        right: 100%; /* Оставьте это значение 100% */
        margin-right: 10px; /* Оставьте это значение 300px */
        padding: 10px;
        width: auto;
        margin: 0 auto;
        color: gray;
    }
    /* New CSS for the pencil icon */
    .pencil-icon {
        position: absolute;
        top: 10px; /* Adjust this value to position it properly */
        right: 10px; /* Adjust this value to position it properly */
        font-size: 20px;
        /* background-color: lightgray;*/
        color: gray;
        border-radius: 50%; /* Make it a circle */
        width: 0px; /*Ensure a square shape */
        height: 10px; /* Ensure a square shape */
        display: flex;
        align-items: center;
    }

        /* Style for the icon inside the circle */
        .pencil-icon i {
            font-size: 14px; /* Adjust the icon size */
        }
</style>

@foreach (var item in Model.OrderBy(x => x.OrderNumber))
{
    <div class="workText">
        @if (item.Lesson.Course.User != null)
        {
            @if (User.Identity.IsAuthenticated && User.IsInRole("admin") || item.Lesson.Course.User.Id == User.GetUserId())
            {
                <div class="pencil-icon">
                    <a href="@Url.Action("Edit", "TextWork", new {id = item.Id})"><i class="fa fa-pencil" style="color: blueviolet;"></i></a>
                </div>
            }
        }
        <div class="sel">@Html.Raw(item.Task)</div>
        <div class="popup">@item.OrderNumber</div>
    </div>
}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">


<script>
    const triggers = document.querySelectorAll('.sel');
    const popups = document.querySelectorAll('.popup');

    triggers.forEach((sel, index) => {
        sel.addEventListener('mouseenter', () => {
            popups[index].style.display = 'block';
        });

        sel.addEventListener('mouseleave', () => {
            popups[index].style.display = 'none';
        });
    });

</script>